// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.Data.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Description { get; set; }

    public virtual Intern CompanyNavigation { get; set; }

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();
}