// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.Data.Models;

public partial class InterviewsInfo
{
    public int InterviewinfoId { get; set; }

    public DateTime Time { get; set; }

    public string Location { get; set; }

    public string Result { get; set; }

    public string Name { get; set; }

    public string Content { get; set; }

    public int InternId { get; set; }

    public virtual Intern Intern { get; set; }
}