// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.Data.Models;

public partial class Task
{
    public int TaskId { get; set; }

    public string Description { get; set; }

    public int InternId { get; set; }

    public string Name { get; set; }

    public int MentorId { get; set; }

    public virtual Intern Intern { get; set; }

    public virtual Mentor Mentor { get; set; }

    public virtual ICollection<WorkingResult> WorkingResults { get; set; } = new List<WorkingResult>();
}