// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.Data.Models;

public partial class WorkingResult
{
    public int ResultId { get; set; }

    public string CreatedBy { get; set; }

    public double? Rating { get; set; }

    public string Note { get; set; }

    public int MentorId { get; set; }

    public int TaskId { get; set; }

    public int InternId { get; set; }

    public virtual Intern Intern { get; set; }

    public virtual Mentor Mentor { get; set; }

    public virtual Task Task { get; set; }
}